### ISSUE TITLE
Frontend is not commicating with the backend in any meaningful way

### ISSUE THREAD

**Issue by jacsiebs** [TheTabletop/OuterCity#28]
Is the server down?
Can't create new users, login, message, find a user or group

**Comment by gsroka1994** [comment]
Yeah our API isn't hosted yet so the front end has been a bit stranded

**Comment by jacsiebs** [comment]
Gotcha, thanks for letting me know

**Comment by jacsiebs** [comment]
Description:
The back end and front end are not communicating as of now due to the API not being hosted. 

Severity: Blocked

Comments:
This is the root issue for many of the issues raised thus far. It is difficult to test the front end in depth because there is so little feedback after completing an action.
