### ISSUE TITLE
Empty quote prepended to list of games when adding new hero

### ISSUE THREAD

**Issue by ChrisGottsacker** [TheTabletop/OuterCity#51]
![image](https://cloud.githubusercontent.com/assets/20909371/25690091/8613c714-3053-11e7-9b68-7106106dee86.png)

![image](https://cloud.githubusercontent.com/assets/20909371/25690110/a8777d8c-3053-11e7-8c26-509c517aa4c3.png)

**Comment by gsroka1994** [comment]
![image](https://cloud.githubusercontent.com/assets/25554305/25707173/534e2392-30a8-11e7-9bcd-ac0e97bd6da2.png)


I didn't have that issue when creating a hero.  Interesting....
